### PR TITLE
PR WIP - 24 referral program

### PR DESCRIPTION
**Pull request by yenicelik**
#24 So far worked on 

- User can deposit tokens using the `POST /user/balance/:tx_hash` endpoint (prior to that sending coins to the deposit contract) [not yet tested]
- User can check their balance using the ``GET /user/balance` endpoint
- Added deposit_receipt table
- Added balance table
- Added referrer Table (every user, assuming they're premium can generate a referral code)
- Added referee Table (records what referral code a user has redeemed)
- Added endpoint to create a referral link (assuming premium user)
- WIP endpoint to redeem a referral link. This does not yet mean that the user is provided with credit, but rather that the spend-tracking starts. Also we should prob assume that the referred user should not have been signed up already?

What should prob be removed again:
- rpc_request table

What's missing:
- Spend table (this will also control if the referrer will get their extra free tokens, according to whether the referee has )
- After each spending call, we need to check (and deposit) items to the referrer. Add a column to the referee (recognized) to check whether the referee and referrer have both received credits

Please see this PR and not the issue as there were significant changes to the issue.

### CODE REVIEW

**Comment by yenicelik** [comment]
@WyseNynja pointing out any bigger (design) flaws would be helpful

**Comment by yenicelik** [comment]
The workflow looks like this:
(1) X is already a premium user
(2) X creates a referral code
(3) X sends the referral code to Y
(4) Y creates a premium account
(5) Y deposits tokens to receive a balance
(6) Y starts using RPC requests. Each RPC request adds to a "spent" table
(7) After each RPC request, the "spent" table is checked. 
(8) If the spent credits, according to the spent table is above a certain threshold, assign N credits to X, and M credits to Y.
(9) Mark that Y has used up his referral code, they cannot be deposited "free" credits again

**Comment by WyseNynja** [comment]
So we said earlier that a user should only have one referral code. Should we also have it do that once a referral is set, it can't be changed? I think makes the code a lot easier. But maybe not

**Comment by WyseNynja** [comment]
> (8) If the spent credits, according to the spent table is above a certain threshold, assign N credits to X, and M credits to Y.

Why are giving credits to both X and Y?

**Comment by yenicelik** [comment]
> So we said earlier that a user should only have one referral code. Should we also have it do that once a referral is set, it can't be changed? I think makes the code a lot easier. But maybe not

Yes this is the case right now

**Comment by yenicelik** [comment]
Closing as outdated

**Pull request closed without merging**
